# config/accounts.yaml
vault_version: 1
encryption_key: "$VAULT_KEY"  # 从环境变量读取

accounts:
  # 明文账户（不推荐）
  test_account:
    address: "0xB270B2fa0c9033F1d81fc418FBeEc99fe0182F50"
    private_key: "a9cffdf711a32c80927b2c8ffb9e83569317093af619f904e5633b239eb6dd8d"
    networks: ["bsc_testnet"]  # 限制可用网络

  # 加密账户（推荐）
  admin:
    address: "0x544Ae0Cbffbae89EB829aC12569cA54361000323"
#    private_key: "encrypted:gAAAAABkO..."
    private_key: "b7139768c48092f0561402ddc29951a72adde71290f2bf6916ac04455f28d582"
    networks: ["bsc_mainnet", "polygon_mainnet"]
    tags: ["privileged"]

  # 模式生成账户
#  user_%:
#    generator: "mnemonic"     # 生成方式：mnemonic|private_key|keystore
#    mnemonic: "apple banana ..."  # 加密存储
#    count: 5                  # 生成5个账户(user_1到user_5)
#    derivation_path: "m/44'/60'/0'/0/%d"